version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: nimda
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3366:3306"

volumes:
  db_data: