version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: back-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: nimda
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3366:3306"

  temporal-db:
    image: postgres:latest
    container_name: temporal-mysql-container
    environment:
      POSTGRES_PASSWORD: temporalpass
      POSTGRES_USER: root
      POSTGRES_DB: temporal
    volumes:
      - temporal_db_data:/var/lib/mysql
    ports:
      - "5432:5432"

  temporal:
    image: temporalio/auto-setup
    container_name: temporal
    ports:
      - "7233:7233"
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PWD=temporalpass
      - POSTGRES_SEEDS=temporal-db
    depends_on:
      - temporal-db

  temporal-ui:
    image: temporalio/ui:latest
    container_name: temporal-ui
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal

volumes:
  db_data:
  temporal_db_data: